# Configuration for support-requests - https://github.com/dessant/support-requests
supportLabel: invalid
supportComment: This issue tracker is for **confirmed bugs** and **approved feature requests** only. Please review the [Contribution Guidelines](http://redeclipse.net/contribute). If you want to chat, have a feature request, or need help and support, you should use our [Discussion Area](http://redeclipse.net/discuss) or [Live Chat](http://redeclipse.net/chat).
close: true
lock: true
